#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

define("MIGRATIONS_PATH", __DIR__."/app/database/migrations");
define("SEEDS_PATH", __DIR__."/app/database/seeds");

/**
 * Script for creating, destroying, and seeding the app's database
 */
class Novice {

    function __construct($args)
    {
        $this->args = $args;
    }

    function help()
    {
        echo "\n";
        echo "syntaxis: php novice <command> [<args>]".PHP_EOL;
        echo PHP_EOL;

        echo "Commands: \n";
        echo "php novice --help                  -->   Displays the help menu.".PHP_EOL;
        echo "php novice migrate                 -->   Migrate the database.".PHP_EOL;
        echo "php novice seed                    -->   Seed the database tables.".PHP_EOL;
        echo "php novice novice migrate --seed   -->   Migrate and seed the database.".PHP_EOL;
        echo PHP_EOL;
    }

    function exec()
    {
        if (count($this->args) <= 1) {
            $this->help();
        } else {
            switch ($this->args[1]) {
                case "migrate":
                    $this->runMigrations();
                    if (!isset($this->args[2]) || $this->args[2] != '--seed')
                        break;
                case "seed":
                    $this->runSeed();
                    break;
                case "help":
                case "--help":
                    $this->help();
                    break;
            }
        }
    }

    function runMigrations()
    {
        $files = glob(MIGRATIONS_PATH.'/*.php');

        $this->run($files);
    }

    function runSeed()
    {
        $files = glob(SEEDS_PATH.'/*.php');

        $this->run($files);
    }
    
    private function run($files)
    {
        foreach ($files as $file) {
            require_once($file);

            $class = basename($file, '.php');

            $obj = new $class;
            $obj->run();
        }
    }
}

$novice = new Novice($argv);
$novice->exec();
